name: calorie_tracker_app
description: Flutter app for tracking calories

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.5.0
  json_annotation: ^4.0.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  scoped_model: ^1.1.0
  get_it: ^1.0.3
  firebase_core: ^1.10.0
  firebase_database: ^9.0.6
  flutter_spinkit: ^5.1.0
  firebase_auth:
  
dependencies_overrides:
  photo_view: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  assets:
    - images/androidIcon.png
